### ISSUE TITLE
结果面板跟随模式 resultListModeFollowSelect  设置为true以选项无法下拉

### ISSUE THREAD

**Issue by ofriend-jinxin** [baidu/amis#12055]
#### 描述问题：

结果面板跟随模式 resultListModeFollowSelect  设置为true以选项无法下拉

#### 截图或视频：

![Image](https://github.com/user-attachments/assets/75f73d51-d9ea-405e-acd2-5063e2e2d238)

#### 如何复现（请务必完整填写下面内容）：
1、访问 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/transfer
2、在 结果面板跟随模式 处编辑代码
3、复制多个options
4、全选左侧可选项

完整代码如下
```json
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "label": "表格形式",
        "type": "transfer",
        "name": "transfer",
        "selectMode": "table",
        "resultListModeFollowSelect": true,
        "columns": [
          {
            "name": "label",
            "label": "英雄"
          },
          {
            "name": "position",
            "label": "位置"
          }
        ],
        "options": [
          {
            "label": "诸葛亮",
            "value": "zhugeliang",
            "position": "中单"
          },
          {
            "label": "诸2葛亮",
            "value": "zhugel2iang",
            "position": "中单"
          },
          {
            "label": "诸3葛亮",
            "value": "zhuge34liang",
            "position": "中单"
          },
          {
            "label": "诸葛亮",
            "value": "zhu4geliang",
            "position": "中单"
          },
          {
            "label": "曹操",
            "value": "caocao",
            "position": "上单"
          },
          {
            "label": "曹2操",
            "value": "cao2cao",
            "position": "上单"
          },
          {
            "label": "曹3操",
            "value": "cao3cao",
            "position": "上单"
          },
          {
            "label": "钟无艳",
            "value": "zhongwuyan",
            "position": "上单"
          },
          {
            "label": "钟2无艳",
            "value": "zhon2gwuyan",
            "position": "上单"
          },
          {
            "label": "钟无3艳",
            "value": "zhon3gwuyan",
            "position": "上单"
          },
          {
            "label": "钟4无艳",
            "value": "zho4ngwuyan",
            "position": "上单"
          },
          {
            "label": "李白",
            "value": "libai",
            "position": "打野"
          },
          {
            "label": "韩信",
            "value": "hanxin",
            "position": "打野"
          },
          {
            "label": "云中君",
            "value": "yunzhongjun",
            "position": "打野"
          }
        ]
      }
    ]
  }
}
```

**Comment by KevinWen7415** [comment]
解决了吗？遇到了一样的问题

**Comment by KevinWen7415** [comment]
> 解决了吗？遇到了一样的问题

配合AI勉强算是解决了，使用样式覆盖了原本的transfer 下面的selection 的css 样式。
使用外层className 配置一个新的css class

<img width="863" height="330" alt="Image" src="https://github.com/user-attachments/assets/15d304b0-f50c-4c91-8363-70dfbb979f6f" />

然后在项目加载的主题css 中将transfer selection 相关的css 的overflow-y 属性进行覆盖
```css
/* Custom styles for transfer component with fixed height */
.transfer-with-fixed-height {
  height: 400px !important;
}

.transfer-with-fixed-height .cxd-Transfer-result {
  height: 350px !important;
  overflow-y: auto !important;
  display: flex;
  flex-direction: column;
}

.transfer-with-fixed-height .cxd-Selections {
  flex: 1;
  overflow-y: auto !important;
}

.transfer-with-fixed-height .cxd-TableSelection {
  height: 100%;
}

.transfer-with-fixed-height .cxd-Table-content {
  height: 100% !important;
  overflow-y: auto !important;
  overflow-x: hidden !important;
}
```
