### ISSUE TITLE
建议使用yaml配置代替json配置

### ISSUE THREAD

**Issue by rexxiang** [baidu/amis#1660]
建议使用更加精简的yaml语法来代替json语法配置。

好处：
- 更好的可读性
- 语法噪音更少，更干净的代码
- 注释支持更友好
- anchor/alias进一步提高节点的重用

例如：
```json
{
  "type": "page",
  "body": [
    {
      "type": "grid",
      "className": "b-a bg-dark lter",
      "columns": [
        {
          "type": "plain",
          "text": "md: 3",
          "md": 3,
          "className": "b-r"
        },
        {
          "type": "plain",
          "text": "md: 9",
          "md": 9
        }
      ]
    },
    {
      "type": "grid",
      "className": "b-a m-t bg-dark lter",
      "columns": [
        {
          "type": "plain",
          "text": "mdOffset: 3",
          "mdOffset": 3
        }
      ]
    }
  ]
}

```

使用等价的yaml表示
```yaml
type: page
body:
- type: grid
  className: b-a bg-dark lter
  columns:
  - type: plain
    text: 'md: 3'
    md: 3
    className: b-r
  - type: plain
    text: 'md: 9'
    md: 9
- type: grid
  className: b-a m-t bg-dark lter
  columns:
  - type: plain
    text: 'mdOffset: 3'
    mdOffset: 3
```
