### ISSUE TITLE
service 组件提供静默请求

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#2938]
#### 是否关联于某个问题吗：
页面加载的时候去请求一个接口，这个动作只是做一个通知的作用。
页面本身不需要去等待接口的相应，也不需要做什么处理，即便接口错误也无所谓。

#### 预期的解决方案：
因为现在service如果调用失败的话，会有错误提示。
所以希望 service 组件提供静默请求的开关。关闭旋转的菊花，以及错误之后的提示信息。

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/436109/141673417-cf20e69a-a25a-4338-98ef-f2c933d0c80e.png)

没有给service分配空间，是个独节点，所以会有半个菊花。
![image](https://user-images.githubusercontent.com/436109/141673422-0f9f7fd6-cc6b-4024-a20d-7dc71d91a307.png)

**Comment by juqkai** [comment]
用了个简单粗暴的办法模拟了这种效果：
```css
.lazyLoad > .cxd-Spinner, .lazyLoad > .cxd-Alert{
    display: none;
}
```
