### ISSUE TITLE
amis@3.3.0 table 组件 affixHeader=true 时，显示一个错位的阴影

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#7737]
#### 描述问题：

同样的schema，在amis@3.2.0 中没有这个阴影，现在临时用一个全局样式给覆盖掉了相关样式：
```css
.cxd-Table-fixedTop:after {
  box-shadow: none !important;
}

```

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/3793855/676fe238-d0b6-47bf-b9c7-d720ae479edd)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.3.0

3. 引入的相关样式表：
```
import 'amis/lib/themes/cxd.css'
import 'amis/lib/helper.css'
import 'amis/sdk/iconfont.css'
```
