### ISSUE TITLE
word 文档段落对齐方式为 justify 时, 最后一行不管字数多少都会左右对齐排

### ISSUE THREAD

**Issue by zivyuan** [baidu/amis#8569]
#### 描述问题：

word 文档段落对齐方式为 justify 时, 最后一行不管字数多少都会左右对齐排，造成字间距很大。

测试环境：

Mac OS,  Chrome / Safari

Windows, Edge

#### 截图或视频：

<img width="621" alt="image" src="https://github.com/baidu/amis/assets/47002/85d8d085-5a04-41b6-a29f-fbfdf64ef79d">

#### 如何复现（请务必完整填写下面内容）：

1. 打开示例地址： https://aisuda.bce.baidu.com/amis/examples/office-viwewer
2. 上传附件：[contract.docx](https://github.com/baidu/amis/files/13217926/enterprise-contract.docx)

**Comment by zivyuan** [comment]
这个问题看了下源码，当前有对段落最后一行有做过相关处理，但目前似乎未达到效果。
```CSS
.docx-viewer-1 .justify:after {
    content: "";
    display: inline-block;
    width: 100%;
}
```
尝试将 width 改为: `width: 1px;` 后，页面渲染实现了同word一样的效果，段落最后一行没有进行左右对齐。

<img width="581" alt="image" src="https://github.com/baidu/amis/assets/47002/2fba23a3-718d-46af-a852-f792d1cfe0c7">
