### ISSUE TITLE
[3.5.3] transfer 组件数据多了，字体无法完全显示

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#8917]
#### 描述问题：

transfer 组件数据多了，字体无法完全显示

#### 截图或视频：

![CleanShot 2023-11-27 at 23 49 50@2x](https://github.com/baidu/amis/assets/783547/c449d1b9-918e-42ab-b5fc-07820399432c)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.5.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
 let amis = amisRequire('amis/embed');
            // 通过替换下面这个配置来生成不同页面
            let amisJSON = {
                type: 'page',
                title: '表单页面',
                body: [
                    {
                        "label": "多语言",
                        "type": "transfer",
                        "name": "transfer",
                        "searchable": true,
                        "selectMode": "chained",
                        "multiple": true,
                        "source": "./lang.json"
                    }
                ]
            };
            let amisScoped = amis.embed('#root', amisJSON);
```

lang.json 在此。。。
[lang.json](https://github.com/baidu/amis/files/13477278/lang.json)

5. 操作步骤
打开页面就看到了。。。必现的。。。

**Comment by lurunze1226** [comment]
尝试按照这个commit修改一下字体试试呢https://github.com/nwind/amis/commit/1d0539958de456fe51920beb304bfca3caba966f

**Comment by gillbates** [comment]
> 尝试按照这个commit修改一下字体试试呢[nwind@1d05399](https://github.com/nwind/amis/commit/1d0539958de456fe51920beb304bfca3caba966f)

换了，还是不行。。。你那应该可以重现的。。。
mac
chrome: Version 119.0.6045.159 (Official Build) (arm64)
safari: Version 17.1 (19616.2.9.11.7)

都是最新版。。。都有这个问题。。。 @lurunze1226

**Comment by sqzhou** [comment]
全局配置样式
```Css
.cxd-ChainedSelection-itemLabel {
   font-family: -apple-system, 'Noto Sans', 'Helvetica Neue', Helvetica, 'Nimbus Sans L', Arial, 'Liberation Sans', 'PingFang SC', 'Hiragino Sans GB', 'Noto Sans CJK SC', 'Source Han Sans SC', 'Source Han Sans CN', 'Microsoft YaHei', 'Wenquanyi Micro Hei', 'WenQuanYi Zen Hei', 'ST Heiti', SimHei, 'WenQuanYi Zen Hei Sharp', sans-serif;
}
```
这样应该就显示正常了 @gillbates
