### ISSUE TITLE
Select组件弹窗位置错误

### ISSUE THREAD

**Issue by Ladtor** [baidu/amis#9855]
#### 描述问题：

当下拉框位置居于页面靠下位置时，弹窗位置出现错误

#### 截图或视频：

![20240322184545_rec_](https://github.com/baidu/amis/assets/19227210/62ccf077-4df4-447d-9326-d5ea652fd6d1)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
```css
html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
```
```json
[
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "label": "下拉框",
      "name": "select",
      "options":[{
        "value":"Value",
        "label":"Label"
      }],
      "type": "select"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    },
    {
      "type": "textarea"
    }
  ]
```

5. 操作步骤
1. html页面app-wrapper元素使用官方提供的style
2. 下拉框位置居于页面靠下位置
